### ISSUE TITLE
Support task priority

### ISSUE THREAD

**Issue by ayazhafiz** [romgrk/todoist.nvim#15]
Todoist has an option to set task priority. It would be nice if this could be exposed in the plugin somehow, though I'm not sure if the API provides this.

If this sounds like a good idea and I have free time in the next week, I can contribute this.

**Comment by romgrk** [comment]
Hey, sorry about the delay, I was in vacations. Sure it could be nice to expose it. Do you have a suggestion how it could be rendered? And if you still have time to contribute I'd be happy to have your contribution :)

**Comment by ChausseBenjamin** [comment]
Hey @ayazhafiz, you might be interested in [the pr I just submitted](https://github.com/romgrk/todoist.nvim/pull/20). The checkbox color should determine a task's priority (using the same colors that todoist uses).

**Comment by ayazhafiz** [comment]
Wow, I totally missed this thread since my first comment; sorry about that, folks. @ChausseBenjamin it's nice to see that the priority is already exposed by the items returned by the todoist api! Excited for your change if/when it lands.

**Comment by romgrk** [comment]
PR merged.
