### ISSUE TITLE
`:Todoist` isn't a command

### ISSUE THREAD

**Issue by brandoncc** [romgrk/todoist.nvim#16]
For some reason, even after it appears `:TodoistInstall` completes, I don't have a `:Todoist` command. Is there anything you can recommend to try fixing it?

```
Todoist: Installing dependencies...
cd /Users/brandoncc/.config/nvim && npm install
Todoist: Updating remote plugins...
remote/host: node host registered plugins ['fzf-preview.vim', 'todoist', 'vim-be-good']
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /Users/brandoncc/.local/share/nvim/rplugin.vim
Todoist: Done
```

**Comment by smolck** [comment]
I'm also having this issue; it seems that none of the functions defined in the Javascript/Node side of things are defined from within Neovim for some reason (`:TodoistInstall` is one of the commands that does exist because it's defined in VimL). Maybe this is because I'm using Neovim master?

**Comment by brandoncc** [comment]
I also compiled from master, so that could be it @smolck. Thoughts @romgrk?

**Comment by smolck** [comment]
@brandoncc Would you be able to check if it works for you using [Neovim v0.4.3](https://github.com/neovim/neovim/releases/tag/v0.4.3)? I would but my config requires latest master.

**Comment by dhazel** [comment]
Cool plugin. 
Unfortunately my config requires latest master too.

**Comment by brandoncc** [comment]
Maybe I'm not on master, if master is not 0.4.3. This is my build:

```
NVIM v0.4.3
Build type: Debug
LuaJIT 2.0.5
```

**Comment by smolck** [comment]
@brandoncc Yeah master will start with 0.5.0, so I guess that's not part of the problem.

**Comment by romgrk** [comment]
I'm using a master neovim (currently 0.5.0) so that shouldn't be the issue.
I'd try the following to try to solve the issue:
 - Make sure you have the latest `npm install -g neovim` installed (or at least v0.4.9) because previous versions have a bug
 - `:checkhealth` to check if your nodejs setup is chill
 - `cat /Users/brandoncc/.local/share/nvim/rplugin.vim` to see which remote plugins are actually installed
 - if you don't see todoist.nvim's functions/commands, try: `cd path/to/todoist.nvim && node -p 'require(".").toString()` and report any error (this is what neovim runs to generate `rplugin.vim`)

**Comment by brogers** [comment]
I am seeing the same issue as above. 
NVIM v0.4.3
node v13.5.0

Here is the output from the command above:
```
$ node -p 'require(".").toString()'
/Users/brogers24/.local/share/nvim/plugged/todoist.nvim/node_modules/uuid/dist/esm-browser/index.js:1
export { default as v1 } from './v1.js';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:1055:16)
    at Module._compile (internal/modules/cjs/loader.js:1103:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
    at Module.load (internal/modules/cjs/loader.js:988:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1028:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/brogers24/.local/share/nvim/plugged/todoist.nvim/node_modules/todoist/src/v8.js:6:14)
    at Module._compile (internal/modules/cjs/loader.js:1139:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1159:10)
```

**Comment by brogers** [comment]
And here is the output of the `cat` command from the `todoist.nvim` directory:
```
$ cat ../../rplugin.vim
" node plugins
call remote#host#RegisterPlugin('node', '/Users/brogers24/.local/share/nvim/plugged/todoist.nvim/rplugin/node/todoist', [
     \ ])
...
```

**Comment by romgrk** [comment]
I can confirm that I can reproduce the issue. It happens on node 13 but not on node 12 or 14. Is it possible for you to use either of those versions? It looks like some breaking change happened in node 13 that was reverted in node 14, regarding module resolution.

**Comment by brogers** [comment]
👍  That worked for me. Updated to node v14.10.1

Thank you!

**Comment by llinfeng** [comment]
I just learned one other way not to have `:Todoist` to work. From the [Readme for this repo](https://github.com/romgrk/todoist.nvim), sadly, I copied the following line
```
Plug 'romgrk/todoist.vim', { 'do': ':TodoistInstall' }
```
It should be `romgrk/todoist.nvim`. And, no nightly build of `nevom 5.0` is needed. 

----

This is my first attempt to start using `neovim`, and here is a long list of what I learned while simply trying to get `:Todoist` to work. 
1. With [`nvm` ](https://github.com/nvm-sh/nvm#install--update-script), one can pick an arbitrary `node` version.
2. That I can use `python -m pip install -U neovim` to get the "latest vesrion of neovim", and specify the path for both `python2` and `python3`:
    ```
    if has('nvim')
        let g:python3_host_prog = '/usr/bin/python3'
        let g:python_host_prog = '/usr/bin/python'
    endif
    ```
    And, if the bare `python` as found somewhere does not know `pip` command, then one can [install `pip` for `python`](https://pip.pypa.io/en/stable/installing/).
3. `neovim` gives a more detailed `:version` info, using `:checkhealth`. This is cool.
4. The nightly build of `neovim 5.0` is not necessary for `:Todoist` to work. Getting a stable build for `neovim` sufficies:
    ```
    sudo add-apt-repository ppa:neovim-ppa/stable
    sudo apt-get update
    sudo apt install neovim
    ```    
5. That there is another implementation of Vim+Todoist: https://github.com/smolck/nvim-todoist.lua. Though, I had trouble moving the cursor around when I put the two Vim+Todoist addons together using `vim-plug`:
    ```
    " Check out a new repo
    Plug 'nvim-lua/plenary.nvim'
    Plug 'smolck/nvim-todoist.lua'

    let todoist = { 'key': $YOUR_API_KEY }
    " Plug 'romgrk/todoist.nvim'
    Plug 'romgrk/todoist.nvim', { 'do': ':TodoistInstall' }
    ```

----

Glad I caught the typo for `Plug` :) This is a productive Saturday evening!

**Comment by romgrk** [comment]
Thanks! Will update the readme

**Comment by romgrk** [comment]
I've also deprecated `g:todoist.key` (still usable though), using `$TODOIST_API_KEY` is better.

**Comment by comfortablynick** [comment]
I can report I’ve had the same issue on node 10.16.3. All other remote plugins I’ve tried have worked fine, so this is odd.

I also used asdf to install the latest node which is 15.5.1. Same issue; I never get Todoist command.

**Comment by romgrk** [comment]
Does any of the points in https://github.com/romgrk/todoist.nvim/issues/16#issuecomment-679289008 does anything or shows any error?

**Comment by comfortablynick** [comment]
NVIM v0.5.0-dev+1025-g0fad952a2
node v15.5.1

Here is the output of `node -p 'require(".").toString()'`
```js
node:internal/modules/cjs/loader:928
  throw err;
  ^

Error: Cannot find module 'color'
Require stack:
- /home/nick/.local/share/nvim/site/pack/packager/opt/todoist.nvim/src/index.js
- /home/nick/.local/share/nvim/site/pack/packager/opt/todoist.nvim/[eval]
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:925:15)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:997:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/nick/.local/share/nvim/site/pack/packager/opt/todoist.nvim/src/index.js:6:15)
    at Module._compile (node:internal/modules/cjs/loader:1108:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
    at Module.load (node:internal/modules/cjs/loader:973:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:997:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/nick/.local/share/nvim/site/pack/packager/opt/todoist.nvim/src/index.js',
    '/home/nick/.local/share/nvim/site/pack/packager/opt/todoist.nvim/[eval]'
  ]
}
```

Contents of `rplugin.vim`
```vim
" perl plugins


" node plugins
call remote#host#RegisterPlugin('node', '/home/nick/.local/share/nvim/site/pack/packager/opt/todoist.nvim/rplugin/node/todoist', [
     \ ])


" python3 plugins


" ruby plugins


" python plugins
```

**Comment by romgrk** [comment]
Seems like the dependencies might not be installed. Does running `npm install` in todoist's folder fix the issue?

**Comment by RomainSabathe** [comment]
I have the same problem as @comfortablynick (i.e. Cannot find module 'color'). I ran `npm install`, now the output of `node -p 'require(".").toString()'` has changed to:

```javascript
plugin => {
  nvim = global.nvim = plugin.nvim

  const _command  = (...args) => plugin.registerCommand(...args)
  const _function = (...args) => plugin.registerFunction(...args)


  _command('Todoist', pcall(initialize), {
    sync: false,
    nargs: '?',
    complete: 'customlist,Todoist__completeProjects',
  })
  _command('TodoistEval', pcall(input => eval(input)), { sync: false, nargs: 1 })

  _function('Todoist__onCreate',             pcall(onCreate),             { sync: false })
  _function('Todoist__onComplete',           pcall(onComplete),           { sync: false })
  _function('Todoist__onDelete',             pcall(onDelete),             { sync: false })
  _function('Todoist__onIndent',             pcall(onIndent),             { sync: false })
  _function('Todoist__onUnindent',           pcall(onUnindent),           { sync: false })
  _function('Todoist__onChangeContent',      pcall(onChangeContent),      { sync: false })
  _function('Todoist__onChangeDate',         pcall(onChangeDate),         { sync: false })
  _function('Todoist__onChangePriority',     pcall(onChangePriority),     { sync: false })
  _function('Todoist__onRefresh',            pcall(onRefresh),            { sync: false })
  _function('Todoist__onProjectArchive',     pcall(onProjectArchive),     { sync: false })
  _function('Todoist__onProjectDelete',      pcall(onProjectDelete),      { sync: false })
  _function('Todoist__onProjectChangeColor', pcall(onProjectChangeColor), { sync: false })
  _function('Todoist__onProjectChangeName',  pcall(onProjectChangeName),  { sync: false })

  _function('Todoist__listProjects',     pcallSync(listProjects), { sync: true })
  _function('Todoist__completeProjects', pcallSync(completeProjects), { sync: true })

  // Deprecated

  _command('TodoistInit', pcall(() =>
    showWarningMessage('TodoistInit deprecated. Use `:Todoist [project name]` (default "Inbox")')), { sync: false })

  /*
   * plugin.registerAutocmd('BufEnter', async (fileName) => {
   *   await plugin.nvim.buffer.append('BufEnter for a JS File?')
   * }, {sync: false, pattern: '*.js', eval: 'expand("<afile>")'})
   */
}
```
Yet the problem is still the same: running `:Todoist` will always trigger `:TodoistInstall`. Thanks for your help.

I should mention:
- nvim, v0.4.4
- npm v7.76
- node v15.13.0

Interestingly, running `:TodoistEval` returns an `E492: not an editor command`. I don't know if it's expected, I'm not super familiar with how plugins work.

**Comment by RomainSabathe** [comment]
Oddly enough, I think I managed to solve it.
I `cd`ed into `$HOME/.cache/dein/repos/github.com/romgrk/todoist.nvim/src` (or wherever the code for todoist.nvim is available) and I ran `node index.js` there, and a further `npm install` there.
Then I probably had to open/close nvim once or twice and running `:Todoist` each time.

Now I see my Todoist tasks, and I can confirm that they sync properly. Honestly I have no idea why it is solved now.

Something I noticed is that, before the fix, doing something like `node -p "require('color')` would fail. As if the color package wasn't installed. But after running `node index.js`, the `color` package was now mysteriously available. :man_shrugging: 

I'm sure there's an explanation, but my javascript skills are near 0 so everything looks like black magic to me.

**Comment by romgrk** [comment]
Probably the first npm install wasn't in the plugin folder. Also TodoistInstall needs to be run to UpdateRemotePlugins, not sure if dein does it automatically.

**Comment by aprowe** [comment]
I had to cd into `~/.vim/plugged/todoist.nvim/` and run `npm install` to get this to work

**Comment by romgrk** [comment]
`TodoistInstall` does an `npm install` but the error output isn't checked, probably failed for some reason.

**Comment by comfortablynick** [comment]
It's running `npm install`, but it's doing it in the current directory instead of the plugin directory. I can see that clearly when `:TodoistInstall` is run when I have `~/.config/nvim/init.lua` open, for example:
```
Todoist: Installing dependencies...
cd /home/nick/.config/nvim && npm install
Todoist: Updating remote plugins...
remote/host: node host registered plugins ['todoist']
remote/host: python3 host registered plugins []
remote/host: generated rplugin manifest: /home/nick/.local/share/nvim/rplugin.vim
Todoist: Done
```

Similar to @aprowe, if I use my plugin manager to run `npm install`, it works because it runs in the plugin directory.

**Comment by romgrk** [comment]
Weird. I've moved the `expand('<sfile>')` call elsewhere, if it still happens let me know.
