### ISSUE TITLE
API Key: use environment variable instead of config

### ISSUE THREAD

**Issue by romgrk** [romgrk/todoist.nvim#2]
There is less chance of it ending up pushed to a public repo than if it lives in the user's vim config.

**Comment by kkharji** [comment]
Yes, thats an important first issue to start working on. Personally I worked around that by creating a vim file called apis.vim and added it to .gitignore. 

I suggest we have a vimscript that does the following:

(1) checks if `$HOME/.cache/.apis` is readable,  (2) and if it isn’t (2.1) it echos `export TODOIST_API_KEY=“Add your api here”` and then (2.2) append `source $HOME/.cache/.apis` to .bashrc if its readable, .zshrc if readable, or ~/.config/fish/config.fish if readable  (or may just check which shell the user use by reading the value of $SHELL) . Finally (3) Open `$HOME/.cache/.apis` for editing.

To make this more experience friendly and interesting, we can enhance the checking function by promoting the user to input his api key if `$TODOIST_API_KEY` invalid or is empty, then check if its valid and if it is, the function execute the pervious two steps mentioned above, in addition of informing the user where his api key will be stored.

What do you think? Which approach to take and if there a better one?

**Comment by ghost** [comment]
If you don't want to use `process.env.API_KEY`, how about using for instance level-db for storage of the key? Perhaps even worse...

**Comment by romgrk** [comment]
I'd keep it simple, just use `$TODOIST_API_KEY`. Users should be exporting the key from their rc files (`~/.profile`, `$XDG_CONFIG_HOME/environment.d/*.conf`, or `~/.(bash/zsh/...)rc`).

I don't think modifying users' rc files is a good solution in regards to the complexity that it can introduce.

Users are also free to insist and `let $TODOIST_API_KEY = '...'` in neovim but let's encourage the safest practice :)

**Comment by scottyeck** [comment]
This appears to be resolved, correct?

**Comment by romgrk** [comment]
It is, yes.
