### ISSUE TITLE
running `:Todoist <projectname>` makes neovim to crash

### ISSUE THREAD

**Issue by azinsharaf** [romgrk/todoist.nvim#24]
i've installed `todoist.nvim` using `lazy` package manager on `neovim 0.9`. 
```
return {
	'romgrk/todoist.nvim',
	enabled = true,
	event = "VeryLazy",
}
```

`TodoistInstall` ran successfully:
```
Todoist: Installing dependencies...
cd C:/Users/asharaf/AppData/Local/nvim-data/lazy/todoist.nvim && npm install
Todoist: Updating remote plugins...
remote/host: node host registered plugins ['todoist']
remote/host: generated rplugin manifest: C:\Users\asharaf\AppData\Local\nvim-data/rplugin.vim
Todoist: Done
```
i've created an env variable named `TODOIST_API_KEY` with the value from my todoist api key. 

Neovim crashes after running `:Todoist Inbox` or `:Todoist personal` ( i have a `personal` project).

OS: Windows Pro 11

**Comment by romgrk** [comment]
I don't have enough details to reproduce, and I've never tested on windows.

**Comment by azinsharaf** [comment]
ok, thanks, I close this since i can't troubleshoot it.
