### ISSUE TITLE
Please consider marking this project as "As-In" to help folks avoid putting a lot of time in :)

### ISSUE THREAD

**Issue by feoh** [romgrk/todoist.nvim#26]
I am NOT being ungrateful here and hopefully not unappreciative of this open source project you've gifted the world with, but it seems like you've moved on.

I can't get this to install, it has a seemingly rather complicated dependency chain, and it seems from your comments to a couple issues that you're no longer maintaining it.

Might it make sense to mark this unmaintained/as-is just so folks can be aware that the project is perhaps a starting point for future work rather than a currently installable solution for Neovim/Todoist integration?

Thanks in advance and please feel free to disregard if you find this note offensive.

**Comment by romgrk** [comment]
I haven't been using todoist much anymore so I didn't notice the issues. I've fixed an import, which made the plugin work again on my side. I've also added a note on the readme to display the status of the repository.
