### ISSUE TITLE
Responsiveness

### ISSUE THREAD

**Issue by kkharji** [romgrk/todoist.nvim#3]
Hay, I've tested it, so far it works!!, but that response rate is killing me though, idk is it just me or does It actually take 4-5 second to load and another 5-9 second to reflect an action (adding an item or changing its status). In vim environment a second is like a minute. I believe this is a huge draw back, and top priority issue to be solved. a workaround may by letting the user manually pull a copy from the API, store it locally in cache and push it whenever (e.g. done from a working session.)

**Comment by romgrk** [comment]
Yes, the responsiveness will depend on the network :/

However the todoist implementation I wrote does a bit of magic to make development less painful. That however translates in the library doing 2 requests for each request that is made -_- (see note [here](https://github.com/romgrk/node-todoist#closing-note-on-performance))

I guess I'll need to implement things properly now :D 

But alternatively front-end clever tricks can be used to lower the perceived latency from the user. One such trick is to display loading indicators or any kind of feedback to the user ASAP. Normally the plugin already open the buffer ASAP and displays a loading indicator ASAP, is this something you are seeing?
Another clever trick is optimistic updates, meaning that when we reasonably expect the operation to succeed, we update the local state accordingly and display the new state immeditately. State is reverted with an error message only if an error occurs. I will think about it and try to find some time to do some work on this.

**Comment by romgrk** [comment]
I've fixed the first part of the problem, actions now take a single request. I'll look into optimistic updates eventually.
