### ISSUE TITLE
Checkboxes not displaying correctly

### ISSUE THREAD

**Issue by larsthegeek** [romgrk/todoist.nvim#5]
First, nice little utility!  Thanks for creating it.

Likely a font issue or something similar on my side, but the checkboxes all show up as question marks:

![Screenshot 2020-05-29 at 20 50 17](https://user-images.githubusercontent.com/11934/83317980-2992db00-a1ee-11ea-8fe2-06b220b66c25.png)

What about a more org-mode / texty way of showing the checkboxes?

Something like:  
`[  ] Item 1`
`[x] Item 2`
etc.

Not as pretty but perhaps more generally compatible.

**Comment by romgrk** [comment]
Right, I'm using a [nerd font](https://www.nerdfonts.com/font-downloads) I should have been expecting this issue to come up ^^

Sure, I can add a configuration option, what about these defaults?

```
 [ ] Unchecked
 [x] Checked
 […] Loading
 [!] Error
```

**Comment by romgrk** [comment]
I've updated the plugin to add icon [options](https://github.com/romgrk/todoist.nvim#options).

Note that option `g:todoist_api_key` has been renamed to `g:todoist.key`, you'll need to adjust your config. The installation process has also been simplified, with vim-plug:

```vim
Plug 'romgrk/todoist.vim', { 'do': ':TodoistInstall' }
```

Run `:TodoistInstall` manually after updating if you don't use vim-plug.

**Comment by larsthegeek** [comment]
That would be great!  I just redid my neovim config and honestly don’t know what font I have going right now. Ah, the joys of puttering with your tools rather than doing ‘real work’

Cheers,

---
James Peterson, Programmer / SysAdmin / Really Nice Guy™

World Spice Merchants / www.worldspice.com
GPG: A2A0 D226 9740 81CB 8BA1 ACB2 51BF CBAC 67BC BA08
