### ISSUE TITLE
Support multiple projects/switching projects

### ISSUE THREAD

**Issue by romgrk** [romgrk/todoist.nvim#6]

**Comment by romgrk** [comment]
Switching project done.
Need to implement project creation.

**Comment by romgrk** [comment]
Implement project creation, change name & change color.

**Comment by luissolanodev** [comment]
Sorry, is there a way to switch projects withouth having to re-type the command `:Todoist [project_name]`?

**Comment by rickprice** [comment]
There is Clap integration at the bottom of the Readme.md it works well.

You can ping me if you have trouble with that.

Frederick
